name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e3df03f2e3b58b97f61ed18d3dae73948fc1989b14cb9a864855d567e93163"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
