name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c12d093f17ee1e6e99a6de1a7411e29b3520bd7f1bf90329c15367b009984bd7"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
