name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71b6dc01736d175e12827bb58fc641b0fbdfa3c64386239a6faf973f84116c1a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
