name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef389bba845b334cac31f855135a3e3ccc1da5aed1978cc8cd842466936d1f7d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
