name = "Minecraft 1 . 20 Survival Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4b6720c939027d46f51406d038bd28bfea663dcc3aecd989e505ee52957f826"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
