name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0121888333401286dfa29d777bc8d2e4b6421911a0f80e323fafb942e256cdcd"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
