name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c216612819ee41ef844d5d467be0ee7596b42ef8ded54ca9fe20eacb367668db"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = []
