name = "Survival-mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77f286f46a997bd66d0427438f164d4b5e19752cb0fa0f28b166ccbbc481f842"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
